VERSION="2.20.0"                                                    
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

[DOCUMENTATION] 
ORG_NAME="Jasa Pembuatan Online" 
ORG_URL="https://jasa.pembuatan.online" 
ORG_LOGO="https://jasa.pembuatan.online/logo.png" 

[[CURRENCIES]] 
code="JASA" 
issuer="" 
name="JASA" 
display_decimals=2 
image="https://jasa.pembuatan.online/logo.png" 
status="live" 
desc="There will be only 1,000,000 JASA existed on SDEX (Stellar Decentralized Exchange)." 
conditions="JASA will generate dividends as much as 2.5% per month for 10 years." 
redemption_instructions="The dividends send regularly to investor wallets every month." 
fixed_number=1000000 
